### ISSUE TITLE
Convert px to rem in a css var

### ISSUE THREAD

**Issue by Eric-llos** [cuth/postcss-pxtorem#114]
Hello there!

Is there any way to let postcss-pxtorem to convert the css var values? It is not automatically converting my 
```
--text-lg: 16px;
```
to 
```
--text-lg: 1rem;
```

Thanks!

**Comment by malaudha** [comment]
You might have found an answer since you posted, but that works fine on my end.

**Comment by PublicAccountForDev** [comment]
In this case, px are not converted to rem.
```css
body{
   height: var(--el-checkbox-height, 32px)；
}
```
