### ISSUE TITLE
ignore file

### ISSUE THREAD

**Issue by MeCKodo** [cuth/postcss-pxtorem#39]
i want to ignore some file

example
```css
/* pxtorem-ignore */
// then the file will be ignore
...

.div1 {
   width: 100px; // ignored
}
.div2 {
  height: 100px; // ignored
}

...
```

what can i do?
