### ISSUE TITLE
Support for css module `@value`?

### ISSUE THREAD

**Issue by fnlctrl** [cuth/postcss-pxtorem#47]
Hi, thanks for this aweseome plugin!
I'm currently using css modules and found that `@value` rules are not being transformed, for example

```css
@value foo: 16px;
.bar {
  font-size: foo;
  line-height: 32px;
}
```
is transformed to
```css
.bar {
  font-size: 16px;
  line-height: 2em;
}
```
where the `@value` variable is missed out. It would be great if `@value` is supported.
