### ISSUE TITLE
Transform within default variables

### ISSUE THREAD

**Issue by bart-jaskulski** [cuth/postcss-pxtorem#79]
Transforming px values to rem is not working inside default values in custom properties.

CSS below would be sufficient to reproduce the issue.

```css
body {
  padding: var(--site-padding, 16px) 
}
```

Desired outcome should be:

```css
body {
  padding: var(--site-padding, 1rem)
}
```

Nonetheless, such piece of code is not transformed. Is this a flaw possible to fix or design choice?
